sudo: required
services:
  - docker

before_install:
  - docker build -t felipearomani/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run felipearomani/react-test npm run test -- --coverage

after_success:
  - docker build -t felipearomani/multi-client ./client
  - docker build -t felipearomani/multi-nginx ./nginx
  - docker build -t felipearomani/multi-server ./server
  - docker build -t felipearomani/multi-worker ./worker
  # Log in to the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images
  - docker push felipearomani/multi-client
  - docker push felipearomani/multi-nginx
  - docker push felipearomani/multi-server
  - docker push felipearomani/multi-worker