sudo: required
services:
  - docker

before_install:
  - docker build -t felipearomani/react-test -f ./client/Dockerfile.dev .

scripts:
  - docker run felipearomani/react-test npm run test -- --coverage

after_success:
  - docker build -t felipearomani/multi-client -f ./client .
  - docker build -t felipearomani/multi-nginx -f ./nginx .
  - docker build -t felipearomani/multi-server -f ./server .
  - docker build -t felipearomani/multi-worker -f ./worker .
  # Log in to the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images
  - docker push felipearomani/multi-client
  - docker push felipearomani/multi-nginx
  - docker push felipearomani/multi-server
  - docker push felipearomani/multi-worker