sudo: required
services:
  - docker

before_install:
  - docker build -t felipearomani/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run felipearomani/react-test npm run test -- --coverage

after_success:
  - docker build -t felipearomani/multi-client ./client
  - docker build -t felipearomani/multi-nginx ./nginx
  - docker build -t felipearomani/multi-server ./server
  - docker build -t felipearomani/multi-worker ./worker
  # Log in to the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push felipearomani/multi-client
  - docker push felipearomani/multi-nginx
  - docker push felipearomani/multi-server
  - docker push felipearomani/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: romani-multi-docker
  env: RomaniMultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-769177069788
  bucket_path: romani-multi-docker
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY